// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqlwiDhZacKuNKBPcmyagasJub37MlKA',
    appId: '1:936772215906:web:7f266c87345a8293eb9d3b',
    messagingSenderId: '936772215906',
    projectId: 'questarena-35867',
    authDomain: 'questarena-35867.firebaseapp.com',
    storageBucket: 'questarena-35867.firebasestorage.app',
    measurementId: 'G-N0JN39F530',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kMEn3a9MDLk82FTftegxzjVxUfZnjO0',
    appId: '1:936772215906:android:9cdef38e2354cbedeb9d3b',
    messagingSenderId: '936772215906',
    projectId: 'questarena-35867',
    storageBucket: 'questarena-35867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXa0gsv7IoCN4qvMh9JmgCA_VGvLuxd8o',
    appId: '1:936772215906:ios:e9a95ab2922f29b2eb9d3b',
    messagingSenderId: '936772215906',
    projectId: 'questarena-35867',
    storageBucket: 'questarena-35867.firebasestorage.app',
    iosBundleId: 'com.example.questarena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXa0gsv7IoCN4qvMh9JmgCA_VGvLuxd8o',
    appId: '1:936772215906:ios:e9a95ab2922f29b2eb9d3b',
    messagingSenderId: '936772215906',
    projectId: 'questarena-35867',
    storageBucket: 'questarena-35867.firebasestorage.app',
    iosBundleId: 'com.example.questarena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvqlwiDhZacKuNKBPcmyagasJub37MlKA',
    appId: '1:936772215906:web:485f403b5ea76aa5eb9d3b',
    messagingSenderId: '936772215906',
    projectId: 'questarena-35867',
    authDomain: 'questarena-35867.firebaseapp.com',
    storageBucket: 'questarena-35867.firebasestorage.app',
    measurementId: 'G-JTKLYZPFVL',
  );
}
